version: '3.8'

services:
  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
# crie os bancos ead-course e ead-authuser